// The LLM database: a debug log and a translation cache, both disposable.
//
// Same reasoning as the defs cache — everything in here can be regenerated by
// asking the model again, so it stays out of `bb-subsgen-flashcards` and out of
// `backup.ts`. Wiping it costs GPU time and nothing else, which is exactly the
// property the study database does not have.
//
// Both stores are declared at v1 even though `lines` isn't written until the
// translation tier ships. Adding a store later would mean a version bump on a
// database the log viewer and the worker already hold open, for no gain over
// declaring an empty store now.
//
// Openable by the service worker, the study app and the drawer iframe — all
// three run on the extension origin. Content scripts do not, so they go through
// messages, the same as everything else that touches storage.

const DB_NAME = 'bb-subsgen-llm'
const VERSION = 1

export const STORES = {
  log: 'log',
  lines: 'lines',
} as const

/** `dbName` is overridable so tests don't share state. */
export function openLlmDb(dbName = DB_NAME): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(dbName, VERSION)

    req.onupgradeneeded = () => {
      const db = req.result

      const log = db.createObjectStore(STORES.log, { keyPath: 'seq', autoIncrement: true })
      // The viewer reads newest-first; trimming walks oldest-first off the
      // primary key, which is insertion order already.
      log.createIndex('by-at', 'at')

      // Cue identity is positional in memory but not on disk, so the key is the
      // same (video, time) pair `Context` persists — plus the language and model
      // that produced it, because changing either invalidates nothing else.
      const lines = db.createObjectStore(STORES.lines, {
        keyPath: ['bvid', 'lang', 'model', 'start'],
      })
      lines.createIndex('by-video', 'bvid')
    }

    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error)
  })
}

// Memoized for the same reason as flashcardsDb(): the worker is torn down
// whenever it goes idle, so this resolves once per worker lifetime.
let ready: Promise<IDBDatabase> | null = null

export function llmDb(): Promise<IDBDatabase> {
  if (!ready) {
    ready = openLlmDb().catch((e) => {
      // Never cache a failed open, or one transient error poisons the worker.
      ready = null
      throw e
    })
  }
  return ready
}
