// The LLM database: a debug log and a translation cache, both disposable.
//
// Same reasoning as the defs cache — everything in here can be regenerated by
// asking the model again, so it stays out of `bb-subsgen-flashcards` and out of
// `backup.ts`. Wiping it costs GPU time and nothing else, which is exactly the
// property the study database does not have.
//
// Both stores are declared at v1 even though `lines` isn't written until the
// translation tier ships. Adding a store later would mean a version bump on a
// database the log viewer and the worker already hold open, for no gain over
// declaring an empty store now.
//
// Openable by the service worker, the study app and the drawer iframe — all
// three run on the extension origin. Content scripts do not, so they go through
// messages, the same as everything else that touches storage.

import { connection } from '../shared/idb'

const DB_NAME = 'bb-subsgen-llm'

/**
 * 1 — the original schema.
 * 2 — `bvid` becomes `videoId` on `lines`, and `transcripts` arrives. Both
 *     stores are rebuilt empty rather than migrated: see `rebuild`.
 */
const VERSION = 2

export const STORES = {
  log: 'log',
  lines: 'lines',
  transcripts: 'transcripts',
} as const

/**
 * Drops a store if it is there, then creates it fresh.
 *
 * Written to be safe on both paths, so the create and the upgrade can share one
 * line: a brand-new database has nothing to delete, and an existing one has
 * contents that are cheaper to regenerate than to migrate.
 */
function rebuild(db: IDBDatabase, name: string, create: (db: IDBDatabase) => void): void {
  if (db.objectStoreNames.contains(name)) db.deleteObjectStore(name)
  create(db)
}

/** `dbName` is overridable so tests don't share state. */
export function openLlmDb(dbName = DB_NAME): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(dbName, VERSION)

    req.onupgradeneeded = (event) => {
      const db = req.result

      if (event.oldVersion < 1) {
        const log = db.createObjectStore(STORES.log, { keyPath: 'seq', autoIncrement: true })
        // The viewer reads newest-first; trimming walks oldest-first off the
        // primary key, which is insertion order already.
        log.createIndex('by-at', 'at')
      }

      // Everything below is keyed on the video, and the rename to `videoId`
      // moved that key. Both stores are dropped and recreated empty rather than
      // copied across: this database is disposable by design (see the note at
      // the top of the file), so the cost of throwing it away is GPU time on the
      // next viewing and nothing else. The study database next door is the one
      // that gets a careful migration, because it is the one that cannot be
      // rebuilt by asking again.
      rebuild(db, STORES.lines, (fresh) => {
        // Cue identity is positional in memory but not on disk, so the key is
        // the same (video, time) pair `Context` persists — plus the language and
        // model that produced it, because changing either invalidates nothing else.
        const lines = fresh.createObjectStore(STORES.lines, {
          keyPath: ['videoId', 'lang', 'model', 'start'],
        })
        lines.createIndex('by-video', 'videoId')
      })

      // Whisper's output for one video, keyed the same way minus the language:
      // a transcript is the Chinese itself, so there is only ever one per model.
      rebuild(db, STORES.transcripts, (fresh) => {
        const transcripts = fresh.createObjectStore(STORES.transcripts, {
          keyPath: ['videoId', 'model', 'start'],
        })
        transcripts.createIndex('by-video', 'videoId')
      })
    }

    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error)
  })
}

// Memoized for the same reason as flashcardsDb(): the worker is torn down
// whenever it goes idle, so this resolves once per worker lifetime.
export const llmDb = connection(() => openLlmDb())
